### ISSUE TITLE
blastp missing from new docker 2.1.0 image

### ISSUE THREAD

**Issue by kastman** [merenlab/anvio#438]
Hi all,

Thanks for putting up the new docker images. However, it looks like blastp isn't being distributed in the latest version:

    $ docker run -p 8080:8080 -it meren/anvio:2.1.0
     :: anvi'o ::  / >>> anvi-self-test

> :: Reformat the contigs FASTA ...
> 
> Input ........................................: sandbox/contigs.fa
> Output .......................................: /tmp/tmpM7s3Nq/test-output/contigs.fa
> Minimum length ...............................: 0
> Total num contigs ............................: 6
> Total num nucleotides ........................: 57,030
> Contigs removed ..............................: 0 (0.00% of all)
> Nucleotides removed ..........................: 0 (0.00% of all)
> Deflines simplified ..........................: True
> 
> ./run_all_tests.sh: line 19: column: command not found
> 
> ...More tests, then at the end:
> 
> Config Error: An anvi'o function needs 'blastp' to be installed on your system, but it doesn't
>              seem to appear in your path

However, I wonder if this is just indicative of a new test added in 2.1.0; for example the error doesn't appear in 2.0.2 but I also don't see the "Reformat the contigs FASTA ..." section.

Since this is just a local image I suppose it's pretty straightforward to install the blastp depedency (or the diamond blastp?) but since Docker is supposed to be distributable and idempotent I just thought I'd point it out. Thanks for the great work,

Erik

**Comment by meren** [comment]
Oh :/ The reason I missed the 'column: command not found' problem is because I always test the Docker image with `anvi-self-test --suite mini`.

I will try to add all three (column, blast (both NCBI and DIAMOND), and MCL) into the image as soon as possible.

Thank you very much for the report, and sorry for the inconvenience!

**Comment by kastman** [comment]
Thanks for the quick response; glad I wasn't missing something simple! Looking forward to playing with this more,

**Comment by meren** [comment]
Hi Erik, I just pushed a new Docker image for v2.1.0, which should run `anvi-self-test` properly.

Thanks again.

**Comment by kastman** [comment]
Looks great - confirmed that meren/latest self-tests without any problems. 

I do still see that the 2.1.0 tag points to the older commit after a `docker pull`- is this an artifact of the way I downloaded already, or do you need to re-tag somehow? 

    $ docker images -a
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    meren/anvio         latest              327472f5f252        About an hour ago   747.8 MB
    meren/anvio         2.1.0               584b16afe1ca        20 hours ago        667.4 MB
    meren/anvio         2.0.2               4d19f28275cc        5 months ago        672 MB

**Comment by meren** [comment]
I hope that is an artifact! 

Here is what I have:

``` bash
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
meren/anvio         2.1.0               327472f5f252        About an hour ago   747.8 MB
meren/anvio         latest              327472f5f252        About an hour ago   747.8 MB
meren/anvio         2.0.2               4d19f28275cc        5 months ago        672 MB
meren/anvio         2.0.1               b346e015d265        6 months ago        671.9 MB
meren/anvio         1.2.3               88a60781b241        8 months ago        595.2 MB
```

I just removed unused containers and pushed again. I hope it fixes the conflict.

**Comment by kastman** [comment]
Got it - I pulled 2.1.0 again (`docker pull meren/anvio:2.1.0`) and it noticed the newer image. Thanks for the speedy response!
